spring:
  application:
    name: stevil-backend

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  jwt:
    secret: mySuperSecretKeyForStevilProjectWhichIsVeryLongAndSecure12345!
    access-expiration: ${JWT_ACCESS_EXPIRATION:3600000}

  profiles:
    default: local

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

naver:
  search:
    client-id: ${NAVER_API_HUB_CLIENT_ID:}
    client-secret: ${NAVER_API_HUB_CLIENT_SECRET:}
    base-url: https://naverapihub.apigw.ntruss.com

server:
  port: ${SERVER_PORT:8080}