spring:
  application:
    name: stevil-backend

  jwt:
    secret: mySuperSecretKeyForStevilProjectWhichIsVeryLongAndSecure12345!
    access-expiration: ${JWT_ACCESS_EXPIRATION:3600000}

  profiles:
    default: local

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SERVER_PORT:8080}