package com.my.stevil_back.planner;

import com.my.stevil_back.planner.entity.WeeklyPlan;
import com.my.stevil_back.planner.repository.WeeklyPlanRepository;
import com.my.stevil_back.planner.service.PlannerService;
import com.my.stevil_back.user.entity.User;
import com.sun.net.httpserver.HttpServer;
import jakarta.persistence.EntityManager;
import jakarta.persistence.LockModeType;
import jakarta.validation.Validation;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import tools.jackson.databind.ObjectMapper;
import java.net.InetSocketAddress;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import java.util.Optional;
import static com.my.stevil_back.planner.dto.PlannerTypes.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

class PlannerExerciseContractTest {
    private final ObjectMapper json = new ObjectMapper();

    private Preferences preferences() {
        return new Preferences(LocalDate.of(2026,9,7), LocalTime.of(7,0), LocalTime.of(23,0),
                LocalTime.of(8,0), LocalTime.of(12,30), LocalTime.of(18,30), LocalTime.of(19,30), 30,
                List.of(0,2,4), "초보", "가볍게", "", "", "", List.of(), true);
    }

    @Test void pythonExerciseMetadataSurvivesGenerateSaveAndRead() throws Exception {
        // Generated by the current Python schedule() with synthetic activities and a real source row.
        byte[] body;
        try (var stream = getClass().getResourceAsStream("/planner/exercise-draft.json")) {
            assertNotNull(stream); body = stream.readAllBytes();
        }
        var server = HttpServer.create(new InetSocketAddress("127.0.0.1",0),0);
        server.createContext("/plan", exchange -> {
            exchange.getRequestBody().readAllBytes();
            exchange.getResponseHeaders().set("Content-Type","application/json");
            exchange.sendResponseHeaders(200,body.length);
            try (var output = exchange.getResponseBody()) { output.write(body); }
        });
        server.start();
        try (var factory = Validation.buildDefaultValidatorFactory()) {
            var repository = mock(WeeklyPlanRepository.class);
            var em = mock(EntityManager.class);
            var service = new PlannerService(repository, em, json, factory.getValidator(),
                    "http://127.0.0.1:" + server.getAddress().getPort() + "/plan");
            var p = preferences();
            var draft = service.generate(17L,p);
            var exercise = draft.events().stream().filter(e -> "EXERCISE".equals(e.kind())).findFirst().orElseThrow();
            assertEquals("squat", exercise.exerciseId());
            assertEquals("resistance", exercise.exerciseCategory());
            assertEquals("beginner", exercise.exerciseDifficulty());
            assertEquals("bodyweight", exercise.exerciseEquipment());
            assertEquals("low", exercise.exerciseImpact());
            assertEquals("easo-fulltext:table3-r05", exercise.exerciseEvidence().getFirst().evidenceId());
            assertEquals("A", exercise.exerciseEvidence().getFirst().recommendationGrade());
            assertFalse(exercise.exerciseEvidence().getFirst().text().isBlank());
            assertEquals(.75, exercise.exerciseEvidence().getFirst().retrievalScore());
            assertTrue(factory.getValidator().validate(draft).isEmpty());
            when(em.find(User.class,17L,LockModeType.PESSIMISTIC_WRITE)).thenReturn(User.builder().id(17L).build());
            when(repository.findByUserIdAndWeekStart(17L,p.weekStart())).thenReturn(Optional.empty());
            var request = json.readValue(json.writeValueAsString(new Save(0,p,draft.events())), Save.class);
            var saved = service.save(17L,request);
            var captured = ArgumentCaptor.forClass(WeeklyPlan.class);
            verify(repository).save(captured.capture());
            when(repository.findByUserIdAndWeekStart(17L,p.weekStart())).thenReturn(Optional.of(captured.getValue()));
            var reloaded = service.get(17L,p.weekStart());
            assertEquals(saved, reloaded);
            assertEquals(exercise, reloaded.events().stream().filter(e -> e.id().equals(exercise.id())).findFirst().orElseThrow());
        } finally { server.stop(0); }
    }

    @Test void legacyEventsAndBothOldConstructorsRemainCompatible() {
        var original = new Event("legacy","EXERCISE","걷기","", LocalDate.of(2026,9,7).atTime(19,30),
                LocalDate.of(2026,9,7).atTime(20,0),"가볍게",false);
        var tree = (tools.jackson.databind.node.ObjectNode) json.valueToTree(original);
        for (String field : List.of("exerciseId","exerciseCategory","exerciseDifficulty","exerciseEquipment","exerciseImpact","exerciseEvidence")) tree.remove(field);
        var old = json.treeToValue(tree, Event.class);
        assertNull(old.exerciseId());
        assertEquals(List.of(), old.exerciseEvidence());
        assertEquals(original, old);
        assertEquals(original, new Event(original.id(),original.kind(),original.title(),original.details(),original.start(),original.end(),original.intensity(),false,null));
    }

    @Test void invalidNestedEvidenceIsRejected() throws Exception {
        try (var stream = getClass().getResourceAsStream("/planner/exercise-draft.json");
             var factory = Validation.buildDefaultValidatorFactory()) {
            var draft = json.readValue(stream.readAllBytes(), Draft.class);
            var exercise = draft.events().stream().filter(e -> "EXERCISE".equals(e.kind())).findFirst().orElseThrow();
            var tree = json.valueToTree(exercise);
            ((tools.jackson.databind.node.ObjectNode)tree.path("exerciseEvidence").get(0)).put("url","javascript:alert(1)");
            var invalid = json.treeToValue(tree, Event.class);
            assertFalse(factory.getValidator().validate(invalid).isEmpty());
        }
    }
}
