spring:
  application:
    name: plug-trip-backend

  profiles:
    default: local

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SERVER_PORT:8080}