spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/plug_trip_db}
    username: ${DB_USERNAME:plug_trip_user}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug