ARG POSTGRES_BASE=postgres:17-alpine
FROM ${POSTGRES_BASE}
RUN apk add --no-cache --virtual .vector-build build-base git \
    && git clone --depth 1 --branch v0.8.6 https://github.com/pgvector/pgvector.git /tmp/pgvector \
    && cd /tmp/pgvector \
    && make OPTFLAGS="" with_llvm=no \
    && make with_llvm=no install \
    && cd / \
    && rm -rf /tmp/pgvector \
    && apk del .vector-build
